from pathlib import Path
from typing import Dict, Any, List, Optional
from src.graph.query_engine import QueryEngine
from src.workspace import read_file_raw, get_repo_stats, resolve_repo_path

class ContextPacker:
    def __init__(self, query_engine: Optional[QueryEngine] = None):
        self.qe = query_engine or QueryEngine()

    def pack_overview(self, repo: str) -> str:
        """
        Creates an architectural overview context pack for LLM (~2000 tokens).
        """
        repo_key = repo.lower().strip()
        stats = get_repo_stats(repo_key)
        crates = self.qe.get_crates(repo_key)
        sg = self.qe.get_symbol_graph(repo_key)
        entry_points = sg.find_entry_points()

        md = [
            f"# Architectural Overview Context Pack: {repo.upper()}",
            f"> Generated by Custos Nexus (AST and call-graph index)",
            "",
            "## 1. Repository Dimensions",
            f"- **Total Files:** {stats['total_files']}",
            f"- **Total Lines of Code:** {stats['total_lines']:,}",
            f"- **Languages:** {', '.join(f'{k} ({v} files)' for k, v in stats['language_files'].items() if v > 0)}",
            "",
            "## 2. Workspace Crates & Architecture Topology",
            f"The codebase contains **{len(crates)} crates/modules**:",
        ]

        mg = self.qe.get_module_graph(repo_key)
        for c in crates[:25]:
            deps = mg.dependencies_of(c)
            dep_str = f" → depends on `[{', '.join(deps)}]`" if deps else ""
            p = mg.get_crate_path(c)
            md.append(f"- **`{c}`** (`{p}`){dep_str}")

        if len(crates) > 25:
            md.append(f"- ... and {len(crates) - 25} more crates.")

        md.extend([
            "",
            "## 3. Discovered Entry Points",
        ])
        for ep in entry_points[:10]:
            md.append(f"- **`{ep['symbol']}`** in `{ep['file']}` (Line {ep['line']}): `{ep['signature']}`")

        return "\n".join(md)

    def pack_crate(self, repo: str, crate_name: str) -> str:
        """
        Creates a deep crate context pack: purpose, dependencies, key symbols.
        """
        repo_key = repo.lower().strip()
        mg = self.qe.get_module_graph(repo_key)
        crate_info = self.qe.get_crate_deps(crate_name, repo_key)

        crate_path = crate_info.get("path")
        if not crate_path:
            return f"Error: Crate '{crate_name}' not found in repo '{repo}'."

        symbols = self.qe.search_symbols(crate_name, repo=repo_key, limit=30)
        
        md = [
            f"# Crate Context Pack: {crate_name}",
            f"- **Repository:** `{repo.upper()}`",
            f"- **Relative Path:** `{crate_path}`",
            f"- **Internal Dependencies:** {', '.join(f'`{d}`' for d in crate_info['depends_on']) or 'None'}",
            f"- **Depended on by:** {', '.join(f'`{d}`' for d in crate_info['depended_by']) or 'None'}",
            "",
            "## Key Exported Symbols & Traits",
        ]

        for s in symbols:
            scope = f"{s['container']}::" if s.get('container') else ""
            md.append(f"### `[{s['kind']}] {scope}{s['name']}`")
            md.append(f"- **File:** `{s['file_path']}:{s['start_line']}-{s['end_line']}`")
            if s.get("signature"):
                md.append(f"```rust\n{s['signature']}\n```")
            if s.get("docstring"):
                md.append(f"> {s['docstring']}\n")

        return "\n".join(md)

    def pack_function(self, repo: str, symbol_name: str) -> str:
        """
        Creates a 360-degree context pack for a function:
        code snippet, signature, docstring, callers, and callees.
        """
        repo_key = repo.lower().strip()
        details = self.qe.get_symbol_detail(symbol_name, repo=repo_key)
        if not details:
            return f"Symbol '{symbol_name}' not found in repo '{repo}'."

        md = []
        for s in details[:3]:
            container_str = f"{s['container']}::" if s.get('container') else ""
            full_name = f"{container_str}{s['name']}"
            md.append(f"# Symbol Context Pack: {full_name}")
            md.append(f"- **Kind:** `{s['kind']}` ({s['visibility']})")
            md.append(f"- **Location:** `{s['file_path']}` (Lines {s['start_line']}–{s['end_line']})")
            
            if s.get("docstring"):
                md.append(f"\n### Documentation\n{s['docstring']}\n")

            if s.get("signature"):
                md.append(f"### Signature\n```rust\n{s['signature']}\n```")

            # Extract source code
            try:
                content, _, _ = read_file_raw(repo_key, s["file_path"])
                lines = content.splitlines()
                s_idx = max(0, s["start_line"] - 1)
                e_idx = min(len(lines), s["end_line"])
                code_lines = lines[s_idx:e_idx]
                md.append(f"### Implementation\n```rust\n" + "\n".join(code_lines) + "\n```")
            except Exception:
                pass

            # Callers
            callers = s.get("callers", [])
            md.append(f"### Direct Callers ({s.get('caller_count', len(callers))})")
            if callers:
                for c in callers[:10]:
                    md.append(f"- `← {c['caller']}` in `{c['file']}`")
            else:
                md.append("- No callers detected in workspace (or invoked dynamically/via macro).")

            # Callees
            callees = s.get("callees", [])
            md.append(f"### Callees Invoked Inside Body ({s.get('callee_count', len(callees))})")
            if callees:
                for c in callees[:12]:
                    md.append(f"- `→ {c['callee']}`")
            else:
                md.append("- No function calls detected in body.")

            md.append("\n---\n")

        return "\n".join(md)

    def pack_flow(self, repo: str, from_symbol: str, to_symbol: str) -> str:
        """
        Creates an execution trace context pack from from_symbol to to_symbol.
        """
        repo_key = repo.lower().strip()
        paths = self.qe.trace_flow(from_symbol, to_symbol, repo=repo_key)
        if not paths:
            return f"No call path found between '{from_symbol}' and '{to_symbol}' in repo '{repo}'."

        md = [
            f"# Execution Flow Trace: `{from_symbol}` → `{to_symbol}`",
            f"- **Repository:** `{repo.upper()}`",
            f"- **Discovered Paths:** {len(paths)}",
            "",
            "## Shortest Execution Path",
        ]

        shortest = paths[0]
        for step_idx, node in enumerate(shortest, start=1):
            arrow = "🏁 " if step_idx == len(shortest) else ("🚀 " if step_idx == 1 else "  ↓ ")
            md.append(f"{arrow}**Step {step_idx}:** `{node}`")

        return "\n".join(md)

    def pack_file_deep(self, repo: str, file_path: str) -> str:
        """
        Deep structural breakdown of a file: all symbols, lines, and signatures.
        """
        repo_key = repo.lower().strip()
        symbols = self.qe.get_file_symbols(file_path, repo_key)
        
        try:
            content, total_lines, size = read_file_raw(repo_key, file_path)
        except Exception as e:
            return f"Error reading file '{file_path}': {str(e)}"

        md = [
            f"# File Deep Dive: `{file_path}`",
            f"- **Repository:** `{repo.upper()}`",
            f"- **Total Lines:** {total_lines} | **Size:** {size:,} bytes",
            f"- **Total Symbols:** {len(symbols)}",
            "",
            "## Symbol Table",
            "| Kind | Scope | Name | Visibility | Lines |",
            "|---|---|---|---|---|",
        ]

        for s in symbols:
            scope = s['container'] or '-'
            md.append(f"| `{s['kind']}` | `{scope}` | **`{s['name']}`** | `{s['visibility']}` | L{s['start_line']}–L{s['end_line']} |")

        md.extend([
            "",
            "## Detailed Signatures & Descriptions",
        ])

        for s in symbols:
            scope_prefix = f"{s['container']}::" if s.get('container') else ""
            md.append(f"### `{s['kind']} {scope_prefix}{s['name']}` (L{s['start_line']}–L{s['end_line']})")
            if s.get("signature"):
                md.append(f"```rust\n{s['signature']}\n```")
            if s.get("docstring"):
                md.append(f"> {s['docstring']}\n")

        return "\n".join(md)
