[package]
name = "custos-adapter-judgment-jev"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "TypeSafe Jev Judgment Engine"

[dependencies]
custos-core-domain = { workspace = true }
custos-judgment-contracts = { workspace = true }
async-trait = { workspace = true }
